name = "self-evolve-ai"
main = "src/worker.ts"
compatibility_date = "2025-01-01"
account_id = "049ff5e84ecf636b53b162cbb580aae6"

[[kv_namespaces]]
binding = "EVOLVE_KV"
id = "163bb348e58142a2a009f21b2f0ebab0"
